### ISSUE TITLE
C++ should add "Accelerated C++" by Koenig/Moo and current C++14ish Meyers

### ISSUE THREAD

**Issue by PeterSommerlad** [accu-org/essential-books#2]
How to change that page. I am too lazy to do pull requests.

**Comment by chrisoldwood** [comment]
Send me the text by email and I'll edit on your behalf if it's easier.

**Comment by PeterSommerlad** [comment]
The template guide should be the new 2nd edition. Otherwise thanks.

**Comment by chrisoldwood** [comment]
Fixed.
