### ISSUE TITLE
Stale links to ACCU website

### ISSUE THREAD

**Issue by ahtotruu** [accu-org/essential-books#4]
With the recent reorganization of the ACCU website, almost all the links to it from the wiki pages were broken.

Since there does not seem to be a way to fork a wiki and create pull requests for it, I just copied the wiki into a separate repository and updates to https://github.com/ahtotruu/accu-essential-books-wiki.

**Comment by chrisoldwood** [comment]
Can I just give you rights to edit the wiki directly, I trust you 🙂 .

**Comment by ahtotruu** [comment]
That would work well for me. I'll try not to spoil anything. :)

**Comment by chrisoldwood** [comment]
@martinmoene do you have that kind of power or has the mantle been passed on? (I can't see where I would make this happen so I'm guessing I don't have that level of permissions.)

**Comment by martinmoene** [comment]
@chrisoldwood Bob asked me about access, so I'll leave it there for now (it look like I still have more than enough permissions :) 

It's an interesting question how to accept changes to the Wiki. From the commit logs it seems I may only have started the Wiki in January 2014 [1].

On other projects I clone the Wiki, update it locally and push it, however I am at a loss how I (would) process contributions from others (cannot remember if it is possible to use the PR system).

[1] https://github.com/accu-org/essential-books.wiki.git

**Comment by chrisoldwood** [comment]
Maybe doing it as a wiki was a mistake and we should have just done it all in the main repo. Perhaps we should export the wiki and force push it over `master` and then fix up the wiki pages to link to the main repo in case anyone bookmarked them, i.e. swap the source and wiki over 🙂.

**Comment by ahtotruu** [comment]
There's some submodule trickery you could use to make it work for wiki also, I'll try to find the reference later today. But perhaps the swap is still easier to manage in the long run.

**Comment by ahtotruu** [comment]
There's some submodule trickery you could use to make it sort of work for wiki also, but I have lost the link. Perhaps the swap is still easier to manage in the long run. :)
